name: intellij
channels:
  - plotly
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - tensorflow
  - tensorflow-datasets
  - plotly
  - dash
  - dash_core_components
  - dash_html_components
  - dash-bootstrap-components
  - ipython
  - ipywidgets
  - pil