name: dnnviewer
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - tensorflow>=2.0
  - tensorflow-datasets
  - plotly>=4.0
  - dash
  - dash_core_components
  - dash_html_components
  - dash-bootstrap-components
  - flask
  - pillow